-- ============================================================================
-- 🚀 PART 1: SCHEMA SETUP (Create Tables & RLS)
-- ============================================================================
-- Run this script FIRST to set up your database structure.
-- ============================================================================

-- Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    grade INTEGER,
    section TEXT,
    department TEXT,
    birthday DATE,
    avatar_url TEXT,
    attendance_status TEXT DEFAULT 'Absent',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT students_email_unique UNIQUE (email)
);

-- Teachers Table
CREATE TABLE IF NOT EXISTS teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    avatar_url TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT teachers_email_unique UNIQUE (email)
);

-- Parents Table
CREATE TABLE IF NOT EXISTS parents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    avatar_url TEXT,
    user_id TEXT, 
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT parents_email_unique UNIQUE (email)
);

-- Relationships
CREATE TABLE IF NOT EXISTS parent_children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES parents(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    UNIQUE(parent_id, student_id)
);

CREATE TABLE IF NOT EXISTS teacher_subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    subject TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS teacher_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    class_name TEXT NOT NULL
);

-- Student Fees (Corrected Column Names)
CREATE TABLE IF NOT EXISTS student_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    total_fee NUMERIC DEFAULT 0,  -- Matches frontend 'amount' mapping
    paid_amount NUMERIC DEFAULT 0, -- Matches DB standard
    title TEXT,
    due_date DATE,
    term TEXT,
    status TEXT,
    payment_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Other Tables
CREATE TABLE IF NOT EXISTS student_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    status TEXT NOT NULL,
    class_name TEXT,
    UNIQUe(student_id, date)
);

-- Notices Table
CREATE TABLE IF NOT EXISTS notices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT,
    category TEXT,
    is_pinned BOOLEAN DEFAULT FALSE,
    audience JSONB DEFAULT '["all"]'::jsonb,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    class_name TEXT,
    subject TEXT,
    due_date TIMESTAMPTZ,
    total_students INTEGER DEFAULT 0,
    submissions_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade INTEGER,
    section TEXT,
    department TEXT,
    subject TEXT,
    student_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name TEXT,
    day TEXT,
    time TEXT,
    subject TEXT,
    teacher TEXT
);

CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT,
    date DATE,
    time TEXT,
    class_name TEXT,
    subject TEXT,
    is_published BOOLEAN DEFAULT FALSE,
    teacher_id BIGINT REFERENCES teachers(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    student_id BIGINT REFERENCES students(id),
    category TEXT,
    title TEXT,
    summary TEXT,
    related_id BIGINT,
    is_read BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PART 2: ROW LEVEL SECURITY (RLS)
-- ============================================
-- Enable RLS
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE parents ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE timetable ENABLE ROW LEVEL SECURITY;

SELECT '✅ Schema Setup Complete!' as status;
