-- Migration 0047: Parent Module Support - Behavior Records & Report Cards

-- 1. BEHAVIOR RECORDS
DROP TABLE IF EXISTS behavior_records CASCADE;
CREATE TABLE behavior_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    type VARCHAR(50) NOT NULL CHECK (type IN ('Positive', 'Negative')),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    reporter_id UUID REFERENCES auth.users(id),
    reporter_name VARCHAR(255),
    suggestions TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE behavior_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents can view behavior records of their children" ON behavior_records
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM parent_children pc
            JOIN parents p ON p.id = pc.parent_id
            WHERE pc.student_id = behavior_records.student_id
            AND p.user_id::text = auth.uid()::text
        )
    );

CREATE POLICY "Teachers can view behavior records" ON behavior_records
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM teachers t
            WHERE t.user_id = auth.uid()
        )
    );

CREATE POLICY "Teachers can insert behavior records" ON behavior_records
    FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM teachers t
            WHERE t.user_id = auth.uid()
        )
    );

-- 2. REPORT CARDS
DROP TABLE IF EXISTS report_cards CASCADE;
CREATE TABLE report_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE CASCADE,
    term VARCHAR(50) NOT NULL,
    session VARCHAR(50) NOT NULL,
    teacher_comment TEXT,
    principal_comment TEXT,
    attendance_total INTEGER DEFAULT 0,
    attendance_present INTEGER DEFAULT 0,
    attendance_absent INTEGER DEFAULT 0,
    attendance_late INTEGER DEFAULT 0,
    status VARCHAR(20) DEFAULT 'Draft', -- Draft, Submitted, Published
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(student_id, term, session)
);

ALTER TABLE report_cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents view published report cards" ON report_cards
    FOR SELECT
    USING (
        status = 'Published' AND
        EXISTS (
            SELECT 1 FROM parent_children pc
            JOIN parents p ON p.id = pc.parent_id
            WHERE pc.student_id = report_cards.student_id
            AND p.user_id::text = auth.uid()::text
        )
    );

CREATE POLICY "Teachers manage report cards" ON report_cards
    USING (
        EXISTS (
            SELECT 1 FROM teachers t
            WHERE t.user_id = auth.uid()
        )
    );

-- Seed Data (Behavior)
INSERT INTO behavior_records (student_id, date, type, title, description, reporter_name, suggestions)
SELECT id, CURRENT_DATE - INTERVAL '2 days', 'Positive', 'Excellent Participation', 'Active contributor in Math class.', 'Mr. Johnson', ARRAY['Continue encouraging group leadership']
FROM students
WHERE id = 1
AND NOT EXISTS (SELECT 1 FROM behavior_records WHERE student_id = students.id);

INSERT INTO behavior_records (student_id, date, type, title, description, reporter_name, suggestions)
SELECT id, CURRENT_DATE - INTERVAL '5 days', 'Negative', 'Late Arrival', 'Arrived 15 minutes late to first period.', 'Mrs. Smith', ARRAY['Ensure early departure from home']
FROM students
WHERE id = 1
AND NOT EXISTS (SELECT 1 FROM behavior_records WHERE title = 'Late Arrival' AND student_id = students.id);

-- Seed Data (Report Card)
INSERT INTO report_cards (student_id, term, session, teacher_comment, principal_comment, attendance_total, attendance_present, status)
SELECT id, 'First Term', '2025/2026', 'Excellent work this term.', 'A promoted student.', 60, 58, 'Published'
FROM students
WHERE id = 1
AND NOT EXISTS (SELECT 1 FROM report_cards WHERE student_id = students.id AND term = 'First Term');
