-- MANUAL FIX V5: RESET & RECREATE CBT TABLES (The "Nuclear" Fix)
-- Run this if "checks" or "columns" keep failing.
-- This DELETES the questions table and creates it fresh with the CORRECT columns.

BEGIN;

-- 1. Drop the problematic table
DROP TABLE IF EXISTS public.cbt_questions CASCADE;

-- 2. Re-create the table with ALL required columns
CREATE TABLE public.cbt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT REFERENCES public.cbt_exams(id) ON DELETE CASCADE,
    question_text TEXT,
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_option VARCHAR(1),
    marks NUMERIC DEFAULT 1,       -- Supports decimals (e.g. 2.5 marks)
    points NUMERIC DEFAULT 1,      -- Alias for safety
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Disable Security Checks (RLS) to prevent permission errors
ALTER TABLE public.cbt_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbt_questions DISABLE ROW LEVEL SECURITY;

ALTER TABLE public.cbt_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbt_exams DISABLE ROW LEVEL SECURITY;

COMMIT;
