-- MANUAL FIX V6: FINAL UUID FIX
-- The error "incompatible types: bigint and uuid" means your exams table uses UUIDs (Strings) not Numbers.
-- This script adjusts the questions table to match that.

BEGIN;

-- 1. Drop the table that has the wrong type
DROP TABLE IF EXISTS public.cbt_questions CASCADE;

-- 2. Re-create questions table with UUID link
CREATE TABLE public.cbt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id UUID REFERENCES public.cbt_exams(id) ON DELETE CASCADE, -- CHANGED TO UUID
    question_text TEXT,
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_option VARCHAR(1),
    marks NUMERIC DEFAULT 1,
    points NUMERIC DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    cbt_exam_id UUID REFERENCES public.cbt_exams(id) ON DELETE CASCADE -- Backward compat alias
);

-- 3. Disable Security to prevent RLS errors
ALTER TABLE public.cbt_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbt_questions DISABLE ROW LEVEL SECURITY;

ALTER TABLE public.cbt_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cbt_exams DISABLE ROW LEVEL SECURITY;

COMMIT;
