-- MANUAL FIX FOR CHAT AND CBT
-- Run this entire script in your Supabase SQL Editor to fix:
-- 1. Missing Chat Tables (Empty Chat screen)
-- 2. CBT Upload RLS Error (Permission denied error)

BEGIN;

-- ==========================================
-- PART 1: CHAT SCHEMA FIX
-- ==========================================

CREATE TABLE IF NOT EXISTS public.chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) DEFAULT 'direct',
    name VARCHAR(255),
    creator_id BIGINT, 
    last_message_at TIMESTAMPTZ DEFAULT NOW(),
    last_message_text TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.chat_participants (
    room_id BIGINT REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) DEFAULT 'member',
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    last_read_message_id BIGINT,
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL,
    content TEXT,
    type VARCHAR(20) DEFAULT 'text',
    media_url TEXT,
    is_deleted BOOLEAN DEFAULT false,
    is_edited BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Chat
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Permissive Chat Policies (Adjust for production later)
DROP POLICY IF EXISTS "Allow insert participants" ON public.chat_participants;
CREATE POLICY "Allow insert participants" ON public.chat_participants FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow select participants" ON public.chat_participants;
CREATE POLICY "Allow select participants" ON public.chat_participants FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow update participants" ON public.chat_participants;
CREATE POLICY "Allow update participants" ON public.chat_participants FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow insert rooms" ON public.chat_rooms;
CREATE POLICY "Allow insert rooms" ON public.chat_rooms FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow select rooms" ON public.chat_rooms;
CREATE POLICY "Allow select rooms" ON public.chat_rooms FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow update rooms" ON public.chat_rooms;
CREATE POLICY "Allow update rooms" ON public.chat_rooms FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow insert messages" ON public.messages;
CREATE POLICY "Allow insert messages" ON public.messages FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow select messages" ON public.messages;
CREATE POLICY "Allow select messages" ON public.messages FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow update messages" ON public.messages;
CREATE POLICY "Allow update messages" ON public.messages FOR UPDATE USING (true);


-- ==========================================
-- PART 2: CBT EXAMS RLS FIX
-- ==========================================

-- Fix cbt_exams Policies
ALTER TABLE IF EXISTS public.cbt_exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.cbt_exams;
DROP POLICY IF EXISTS "Teachers can create exams" ON public.cbt_exams;
CREATE POLICY "Teachers can create exams" ON public.cbt_exams FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable select for authenticated users" ON public.cbt_exams;
CREATE POLICY "Enable select for authenticated users" ON public.cbt_exams FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable update for creators" ON public.cbt_exams;
CREATE POLICY "Enable update for creators" ON public.cbt_exams FOR UPDATE USING (auth.uid() = teacher_id);

DROP POLICY IF EXISTS "Enable delete for creators" ON public.cbt_exams;
CREATE POLICY "Enable delete for creators" ON public.cbt_exams FOR DELETE USING (auth.uid() = teacher_id);

-- Fix cbt_questions Policies (if table exists)
CREATE TABLE IF NOT EXISTS public.cbt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT REFERENCES public.cbt_exams(id) ON DELETE CASCADE,
    question_text TEXT,
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_option VARCHAR(1),
    marks INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS public.cbt_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Teachers can add questions" ON public.cbt_questions;
CREATE POLICY "Teachers can add questions" ON public.cbt_questions FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable select for authenticated users" ON public.cbt_questions;
CREATE POLICY "Enable select for authenticated users" ON public.cbt_questions FOR SELECT USING (auth.role() = 'authenticated');


COMMIT;
