-- 0048_fix_cbt_rls.sql
-- Purpose: Fix RLS policies preventing CBT Exam creation

-- 1. cbt_exams
ALTER TABLE IF EXISTS public.cbt_exams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.cbt_exams;
DROP POLICY IF EXISTS "Teachers can create exams" ON public.cbt_exams;

CREATE POLICY "Teachers can create exams" ON public.cbt_exams
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable select for authenticated users" ON public.cbt_exams;
CREATE POLICY "Enable select for authenticated users" ON public.cbt_exams
    FOR SELECT
    USING (auth.role() = 'authenticated');
    
DROP POLICY IF EXISTS "Enable update for creators" ON public.cbt_exams;
CREATE POLICY "Enable update for creators" ON public.cbt_exams
    FOR UPDATE
    USING (auth.uid() = teacher_id);

DROP POLICY IF EXISTS "Enable delete for creators" ON public.cbt_exams;
CREATE POLICY "Enable delete for creators" ON public.cbt_exams
    FOR DELETE
    USING (auth.uid() = teacher_id);

-- 2. cbt_questions (Assuming this table exists and is used during upload)
CREATE TABLE IF NOT EXISTS public.cbt_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT REFERENCES public.cbt_exams(id) ON DELETE CASCADE,
    question_text TEXT,
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_option VARCHAR(1),
    marks INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS public.cbt_questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.cbt_questions;
CREATE POLICY "Teachers can add questions" ON public.cbt_questions
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Enable select for authenticated users" ON public.cbt_questions;
CREATE POLICY "Enable select for authenticated users" ON public.cbt_questions
    FOR SELECT
    USING (auth.role() = 'authenticated');

-- 3. cbt_results (Fix potential future error)
CREATE TABLE IF NOT EXISTS public.cbt_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT REFERENCES public.cbt_exams(id) ON DELETE CASCADE,
    student_id BIGINT,
    score INTEGER,
    total_marks INTEGER,
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS public.cbt_results ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Students can insert results" ON public.cbt_results;
CREATE POLICY "Students can insert results" ON public.cbt_results
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "View results" ON public.cbt_results;
CREATE POLICY "View results" ON public.cbt_results
    FOR SELECT
    USING (auth.role() = 'authenticated');
